import type { KnowledgeHelpArticle, HelpCategory } from "../types";

export const HELP_CATEGORIES: HelpCategory[] = ["Start here", "Daily work", "Reports", "Admin"];

const helpMetadata = {
  consumers: ["authenticated-help", "customer-support-ai"],
  visibility: "authenticated",
  safety: "authenticated-user-safe",
} as const;

export const HELP_ARTICLES: KnowledgeHelpArticle[] = [
  {
    key: "product_tour",
    title: "Start with the product tour",
    summary: "Watch the short tour on this page. Then open Grants to start.",
    category: "Start here",
    aliases: ["video", "tour", "walkthrough", "overview", "product video"],
    steps: [
      "Watch the product tour at the top of this page.",
      "See one grant go from new to final report.",
      "Then open Grants and add your first one.",
    ],
    cta: { label: "Open Grants to start", to: "/grants" },
    searchText: "product tour video walkthrough overview grant workflow",
    ...helpMetadata,
  },
  {
    key: "first_setup",
    title: "Set up your workspace",
    summary: "Add your organization basics first. Reports and reminders will use the right dates.",
    category: "Start here",
    aliases: ["first time setup", "where do I start", "new account"],
    steps: [
      "Open Settings and confirm the organization name.",
      "Check the timezone. Grant deadlines use this setting.",
      "Invite one teammate only after the basics look right.",
    ],
    cta: { label: "Open settings", to: "/settings", roles: ["admin"] },
    searchText: "setup organization timezone settings first workspace",
    ...helpMetadata,
  },
  {
    key: "import_contacts",
    title: "Import contacts from a spreadsheet",
    summary: "Bring contacts into GrantPipe from a CSV file. Add donor names and email addresses.",
    category: "Start here",
    aliases: ["spreadsheet", "excel", "upload list", "old crm"],
    steps: [
      "Export your old list as a CSV file. CSV is a plain spreadsheet format.",
      "Open Import, choose Contacts, and paste the CSV contents.",
      "Preview before committing. Nothing is saved until you choose Commit import.",
    ],
    cta: { label: "Open import", to: "/import", roles: ["admin", "editor"] },
    searchText: "csv spreadsheet import contacts donors excel",
    ...helpMetadata,
  },
  {
    key: "record_donation",
    title: "Record a donation",
    summary: "Log gifts from a donor profile. Giving history and reports stay connected.",
    category: "Daily work",
    aliases: ["gift", "check", "cash", "money from donor"],
    steps: [
      "Open Donors and choose the person or organization that gave.",
      "Use the donation area on the donor record.",
      "Enter the amount in dollars. GrantPipe stores the exact cents behind the scenes.",
    ],
    cta: { label: "Open donors", to: "/donors", roles: ["admin", "editor"] },
    searchText: "record donation gift donor receipt amount",
    ...helpMetadata,
  },
  {
    key: "track_pledges",
    title: "Track a donor pledge",
    summary: "Use pledges for promises to give over time. Payments lower the balance.",
    category: "Daily work",
    aliases: ["pledge tracker", "promise to give", "installments", "pledge payment"],
    steps: [
      "Open Pledges from Donors.",
      "Choose New pledge and pick the donor.",
      "Add the pledge date, rate, and installment dates.",
      "Use the status filter.",
      "Pick a status.",
      "Open a pledge. Record a payment, set an allowance, or write it off.",
    ],
    cta: {
      label: "Open pledges",
      to: "/donors/pledges",
      roles: ["admin", "editor", "viewer"],
    },
    searchText: "pledge tracker donor promise payment allowance write off status",
    ...helpMetadata,
  },
  {
    key: "create_grant",
    title: "Create a grant record",
    summary: "Start a grant record when you are researching, applying, or managing an award.",
    category: "Daily work",
    aliases: ["award", "application", "deadline", "funder opportunity"],
    steps: [
      "Open Grants and choose Add grant.",
      "Give the grant a plain name your team will recognize.",
      "Connect it to the funder. Reporting and activity stay in one place.",
    ],
    cta: { label: "Open grants", to: "/grants", roles: ["admin", "editor"] },
    searchText: "create grant award funder application deadline",
    ...helpMetadata,
  },
  {
    key: "restricted_funds",
    title: "Track restricted funds",
    summary: "Use funds to separate money that can only be spent for a specific purpose.",
    category: "Daily work",
    aliases: ["restricted money", "donor restriction", "fund balance"],
    steps: [
      "Open Funds to see balances by restriction.",
      "Create a restricted fund for money tied to a donor purpose or grant agreement.",
      "Use allocations when a grant needs to draw from more than one fund.",
    ],
    cta: {
      label: "Open funds",
      to: "/funds",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText: "restricted funds balances allocations purpose",
    ...helpMetadata,
  },
  {
    key: "budget_sentinel",
    title: "Check budget risks",
    summary: "See grant lines and restricted funds that need a closer look.",
    category: "Daily work",
    aliases: ["budget sentinel", "overspend", "near limit", "fund lapse", "budget alert"],
    steps: [
      "Open Budget Sentinel from Grants.",
      "Filter by overspend or underspend when you need a shorter list.",
      "Open the grant or fund row to check the detail.",
    ],
    cta: {
      label: "Open Budget Sentinel",
      to: "/grants/sentinel",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText: "budget sentinel overspend underspend near limit fund lapse alert",
    ...helpMetadata,
  },
  {
    key: "generate_report",
    title: "Generate a report",
    summary: "Create board, audit, IRS, acknowledgment, and grant compliance files from Reports.",
    category: "Reports",
    aliases: ["pdf", "download", "export", "board packet", "audit"],
    steps: [
      "Open Reports and choose the type you need.",
      "Fill in the fiscal year or grant field.",
      "Generate the report, then open it from Recently generated when it is ready.",
    ],
    cta: {
      label: "Open reports",
      to: "/reports",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText: "generate report board audit IRS grant compliance receipt",
    ...helpMetadata,
  },
  {
    key: "statement_of_activities_report",
    title: "Use the Statement of Activities",
    summary:
      "Review revenue, expenses, and net asset changes for a period. Use this for audits and board reporting.",
    category: "Reports",
    aliases: ["activities report", "net assets", "revenue and expenses", "audit report"],
    steps: [
      "Open the Statement of Activities from Accounting reports.",
      "Choose the reporting period your board, auditor, or grant file needs.",
      "Generate the report and review revenue, releases from restrictions, expenses, and ending net assets.",
    ],
    cta: {
      label: "Open Statement of Activities",
      to: "/accounting/reports/activities",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText: "statement activities revenue expenses changes net assets audit board",
    ...helpMetadata,
  },
  {
    key: "functional_expenses_report",
    title: "Use the Statement of Functional Expenses",
    summary:
      "Review costs split across program services, management, and fundraising. Use this for Form 990 and audit support.",
    category: "Reports",
    aliases: ["functional expenses", "program management fundraising", "irs 990", "form 990"],
    steps: [
      "Open the Statement of Functional Expenses from Accounting reports.",
      "Choose the period that matches the filing, audit, or board package.",
      "Review expense allocation across program, management, and fundraising columns. Then export.",
    ],
    cta: {
      label: "Open Statement of Functional Expenses",
      to: "/accounting/reports/functional-expenses",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText:
      "statement functional expenses program services management fundraising form 990 IRS audit",
    ...helpMetadata,
  },
  {
    key: "open_pdf_report",
    title: "Open a downloaded report",
    summary: "Find the PDF after it downloads. Open it even if your browser hides it.",
    category: "Reports",
    aliases: ["lost download", "where did my pdf go", "downloads folder", "file disappeared"],
    steps: [
      "After downloading, look at the top or bottom of your browser for the file.",
      "If you do not see it, open the Downloads folder on your computer.",
      "Double-click the file to open it. If it will not open, install Adobe Reader or ask your IT person.",
    ],
    cta: {
      label: "Open reports",
      to: "/reports",
      roles: ["admin", "editor", "viewer", "auditor"],
    },
    searchText: "pdf download file downloads folder adobe reader open report",
    ...helpMetadata,
  },
  {
    key: "invite_teammate",
    title: "Invite a teammate",
    summary: "Admins can create a private invite link for another staff member.",
    category: "Admin",
    aliases: ["add user", "new teammate", "staff access", "roles"],
    steps: [
      "Open Settings and go to Team.",
      "Pick Viewer for read-only access or Editor for staff who create records.",
      "Copy the invite link and send it directly to the person.",
    ],
    cta: { label: "Open team settings", to: "/settings", hash: "team", roles: ["admin"] },
    searchText: "invite teammate team role admin editor viewer link",
    ...helpMetadata,
  },
];
