/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalHomeRouteImport } from './routes/portal/home'
import { Route as PortalTokenRouteImport } from './routes/portal/$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSelectPlanRouteImport } from './routes/_authenticated/select-plan'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedEvidenceBundlesRouteImport } from './routes/_authenticated/evidence-bundles'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfirmPlanRouteImport } from './routes/_authenticated/confirm-plan'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAccountingRouteImport } from './routes/_authenticated/accounting'
import { Route as AuthenticatedSubrecipientsIndexRouteImport } from './routes/_authenticated/subrecipients/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProgramsIndexRouteImport } from './routes/_authenticated/programs/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedGrantsIndexRouteImport } from './routes/_authenticated/grants/index'
import { Route as AuthenticatedFundsIndexRouteImport } from './routes/_authenticated/funds/index'
import { Route as AuthenticatedFundersIndexRouteImport } from './routes/_authenticated/funders/index'
import { Route as AuthenticatedEvidenceBundlesIndexRouteImport } from './routes/_authenticated/evidence-bundles/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as AuthenticatedDonorsIndexRouteImport } from './routes/_authenticated/donors/index'
import { Route as AuthenticatedDeadlinesIndexRouteImport } from './routes/_authenticated/deadlines/index'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting/index'
import { Route as PortalRestrictionTermsIdRouteImport } from './routes/portal/restriction-terms.$id'
import { Route as PortalProgramsIdRouteImport } from './routes/portal/programs.$id'
import { Route as PortalGrantsIdRouteImport } from './routes/portal/grants.$id'
import { Route as PortalGeneratedReportsIdRouteImport } from './routes/portal/generated-reports.$id'
import { Route as PortalFundsIdRouteImport } from './routes/portal/funds.$id'
import { Route as PortalDocumentsIdRouteImport } from './routes/portal/documents.$id'
import { Route as PortalBundlesIdRouteImport } from './routes/portal/bundles.$id'
import { Route as AuthenticatedSubrecipientsSubrecipientIdRouteImport } from './routes/_authenticated/subrecipients/$subrecipientId'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsPortalAccessRouteImport } from './routes/_authenticated/settings.portal-access'
import { Route as AuthenticatedSettingsEntitiesRouteImport } from './routes/_authenticated/settings.entities'
import { Route as AuthenticatedSettingsBillingRouteImport } from './routes/_authenticated/settings.billing'
import { Route as AuthenticatedReportsDraftsRouteImport } from './routes/_authenticated/reports/drafts'
import { Route as AuthenticatedReportsBuilderRouteImport } from './routes/_authenticated/reports/builder'
import { Route as AuthenticatedReportsAskLedgerRouteImport } from './routes/_authenticated/reports/ask-ledger'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports/$reportId'
import { Route as AuthenticatedProgramsProgramIdRouteImport } from './routes/_authenticated/programs/$programId'
import { Route as AuthenticatedPaymentsRequestIdRouteImport } from './routes/_authenticated/payments/$requestId'
import { Route as AuthenticatedGrantsSentinelRouteImport } from './routes/_authenticated/grants/sentinel'
import { Route as AuthenticatedGrantsPipelineRouteImport } from './routes/_authenticated/grants/pipeline'
import { Route as AuthenticatedGrantsGrantIdRouteImport } from './routes/_authenticated/grants/$grantId'
import { Route as AuthenticatedFundsFundIdRouteImport } from './routes/_authenticated/funds/$fundId'
import { Route as AuthenticatedFundersFunderIdRouteImport } from './routes/_authenticated/funders/$funderId'
import { Route as AuthenticatedEvidenceBundlesBundleIdRouteImport } from './routes/_authenticated/evidence-bundles/$bundleId'
import { Route as AuthenticatedEventsEventIdRouteImport } from './routes/_authenticated/events/$eventId'
import { Route as AuthenticatedDonorsPledgesRouteImport } from './routes/_authenticated/donors/pledges'
import { Route as AuthenticatedDonorsEmailRouteImport } from './routes/_authenticated/donors/email'
import { Route as AuthenticatedDonorsAtRiskRouteImport } from './routes/_authenticated/donors/at-risk'
import { Route as AuthenticatedDonorsContactIdRouteImport } from './routes/_authenticated/donors/$contactId'
import { Route as AuthenticatedDeadlinesCalendarRouteImport } from './routes/_authenticated/deadlines/calendar'
import { Route as AuthenticatedAwardIntakeExtractionIdRouteImport } from './routes/_authenticated/award-intake/$extractionId'
import { Route as AuthenticatedAccountingTrialBalanceRouteImport } from './routes/_authenticated/accounting/trial-balance'
import { Route as AuthenticatedAccountingRecurringRouteImport } from './routes/_authenticated/accounting/recurring'
import { Route as AuthenticatedAccountingPeriodsRouteImport } from './routes/_authenticated/accounting/periods'
import { Route as AuthenticatedAccountingLedgerRouteImport } from './routes/_authenticated/accounting/ledger'
import { Route as AuthenticatedAccountingIntegrationsRouteImport } from './routes/_authenticated/accounting/integrations'
import { Route as AuthenticatedAccountingChartOfAccountsRouteImport } from './routes/_authenticated/accounting/chart-of-accounts'
import { Route as AuthenticatedAccountingAnomaliesRouteImport } from './routes/_authenticated/accounting/anomalies'
import { Route as AuthenticatedAccountingJournalIndexRouteImport } from './routes/_authenticated/accounting/journal/index'
import { Route as AuthenticatedAccountingBankIndexRouteImport } from './routes/_authenticated/accounting/bank/index'
import { Route as AuthenticatedAccountingStudiosFunctionalExpenseAllocationRouteImport } from './routes/_authenticated/accounting/studios/functional-expense-allocation'
import { Route as AuthenticatedAccountingReportsFunctionalExpensesRouteImport } from './routes/_authenticated/accounting/reports/functional-expenses'
import { Route as AuthenticatedAccountingReportsFinancialPositionRouteImport } from './routes/_authenticated/accounting/reports/financial-position'
import { Route as AuthenticatedAccountingReportsActivitiesRouteImport } from './routes/_authenticated/accounting/reports/activities'
import { Route as AuthenticatedAccountingJournalNewRouteImport } from './routes/_authenticated/accounting/journal/new'
import { Route as AuthenticatedAccountingJournalEntryIdRouteImport } from './routes/_authenticated/accounting/journal/$entryId'
import { Route as AuthenticatedAccountingBankBankAccountIdRouteImport } from './routes/_authenticated/accounting/bank/$bankAccountId'
import { Route as AuthenticatedGrantsGrantIdRestrictionsTermIdRouteImport } from './routes/_authenticated/grants/$grantId_.restrictions.$termId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHomeRoute = PortalHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => PortalRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelectPlanRoute = AuthenticatedSelectPlanRouteImport.update({
  id: '/select-plan',
  path: '/select-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvidenceBundlesRoute =
  AuthenticatedEvidenceBundlesRouteImport.update({
    id: '/evidence-bundles',
    path: '/evidence-bundles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfirmPlanRoute =
  AuthenticatedConfirmPlanRouteImport.update({
    id: '/confirm-plan',
    path: '/confirm-plan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountingRoute = AuthenticatedAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubrecipientsIndexRoute =
  AuthenticatedSubrecipientsIndexRouteImport.update({
    id: '/subrecipients/',
    path: '/subrecipients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramsIndexRoute =
  AuthenticatedProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrantsIndexRoute =
  AuthenticatedGrantsIndexRouteImport.update({
    id: '/grants/',
    path: '/grants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFundsIndexRoute = AuthenticatedFundsIndexRouteImport.update({
  id: '/funds/',
  path: '/funds/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFundersIndexRoute =
  AuthenticatedFundersIndexRouteImport.update({
    id: '/funders/',
    path: '/funders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEvidenceBundlesIndexRoute =
  AuthenticatedEvidenceBundlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEvidenceBundlesRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsIndexRoute =
  AuthenticatedDonorsIndexRouteImport.update({
    id: '/donors/',
    path: '/donors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeadlinesIndexRoute =
  AuthenticatedDeadlinesIndexRouteImport.update({
    id: '/deadlines/',
    path: '/deadlines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const PortalRestrictionTermsIdRoute =
  PortalRestrictionTermsIdRouteImport.update({
    id: '/restriction-terms/$id',
    path: '/restriction-terms/$id',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProgramsIdRoute = PortalProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGrantsIdRoute = PortalGrantsIdRouteImport.update({
  id: '/grants/$id',
  path: '/grants/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGeneratedReportsIdRoute =
  PortalGeneratedReportsIdRouteImport.update({
    id: '/generated-reports/$id',
    path: '/generated-reports/$id',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalFundsIdRoute = PortalFundsIdRouteImport.update({
  id: '/funds/$id',
  path: '/funds/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsIdRoute = PortalDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBundlesIdRoute = PortalBundlesIdRouteImport.update({
  id: '/bundles/$id',
  path: '/bundles/$id',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedSubrecipientsSubrecipientIdRoute =
  AuthenticatedSubrecipientsSubrecipientIdRouteImport.update({
    id: '/subrecipients/$subrecipientId',
    path: '/subrecipients/$subrecipientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPortalAccessRoute =
  AuthenticatedSettingsPortalAccessRouteImport.update({
    id: '/portal-access',
    path: '/portal-access',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsEntitiesRoute =
  AuthenticatedSettingsEntitiesRouteImport.update({
    id: '/entities',
    path: '/entities',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsBillingRoute =
  AuthenticatedSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedReportsDraftsRoute =
  AuthenticatedReportsDraftsRouteImport.update({
    id: '/reports/drafts',
    path: '/reports/drafts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsBuilderRoute =
  AuthenticatedReportsBuilderRouteImport.update({
    id: '/reports/builder',
    path: '/reports/builder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsAskLedgerRoute =
  AuthenticatedReportsAskLedgerRouteImport.update({
    id: '/reports/ask-ledger',
    path: '/reports/ask-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgramsProgramIdRoute =
  AuthenticatedProgramsProgramIdRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRequestIdRoute =
  AuthenticatedPaymentsRequestIdRouteImport.update({
    id: '/payments/$requestId',
    path: '/payments/$requestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrantsSentinelRoute =
  AuthenticatedGrantsSentinelRouteImport.update({
    id: '/grants/sentinel',
    path: '/grants/sentinel',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/grants/sentinel.lazy').then((d) => d.Route),
  )
const AuthenticatedGrantsPipelineRoute =
  AuthenticatedGrantsPipelineRouteImport.update({
    id: '/grants/pipeline',
    path: '/grants/pipeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/grants/pipeline.lazy').then((d) => d.Route),
  )
const AuthenticatedGrantsGrantIdRoute =
  AuthenticatedGrantsGrantIdRouteImport.update({
    id: '/grants/$grantId',
    path: '/grants/$grantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFundsFundIdRoute =
  AuthenticatedFundsFundIdRouteImport.update({
    id: '/funds/$fundId',
    path: '/funds/$fundId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFundersFunderIdRoute =
  AuthenticatedFundersFunderIdRouteImport.update({
    id: '/funders/$funderId',
    path: '/funders/$funderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEvidenceBundlesBundleIdRoute =
  AuthenticatedEvidenceBundlesBundleIdRouteImport.update({
    id: '/$bundleId',
    path: '/$bundleId',
    getParentRoute: () => AuthenticatedEvidenceBundlesRoute,
  } as any)
const AuthenticatedEventsEventIdRoute =
  AuthenticatedEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsPledgesRoute =
  AuthenticatedDonorsPledgesRouteImport.update({
    id: '/donors/pledges',
    path: '/donors/pledges',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsEmailRoute =
  AuthenticatedDonorsEmailRouteImport.update({
    id: '/donors/email',
    path: '/donors/email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsAtRiskRoute =
  AuthenticatedDonorsAtRiskRouteImport.update({
    id: '/donors/at-risk',
    path: '/donors/at-risk',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDonorsContactIdRoute =
  AuthenticatedDonorsContactIdRouteImport.update({
    id: '/donors/$contactId',
    path: '/donors/$contactId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeadlinesCalendarRoute =
  AuthenticatedDeadlinesCalendarRouteImport.update({
    id: '/deadlines/calendar',
    path: '/deadlines/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAwardIntakeExtractionIdRoute =
  AuthenticatedAwardIntakeExtractionIdRouteImport.update({
    id: '/award-intake/$extractionId',
    path: '/award-intake/$extractionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingTrialBalanceRoute =
  AuthenticatedAccountingTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingRecurringRoute =
  AuthenticatedAccountingRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingPeriodsRoute =
  AuthenticatedAccountingPeriodsRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingLedgerRoute =
  AuthenticatedAccountingLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingIntegrationsRoute =
  AuthenticatedAccountingIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingChartOfAccountsRoute =
  AuthenticatedAccountingChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingAnomaliesRoute =
  AuthenticatedAccountingAnomaliesRouteImport.update({
    id: '/anomalies',
    path: '/anomalies',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalIndexRoute =
  AuthenticatedAccountingJournalIndexRouteImport.update({
    id: '/journal/',
    path: '/journal/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingBankIndexRoute =
  AuthenticatedAccountingBankIndexRouteImport.update({
    id: '/bank/',
    path: '/bank/',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute =
  AuthenticatedAccountingStudiosFunctionalExpenseAllocationRouteImport.update({
    id: '/studios/functional-expense-allocation',
    path: '/studios/functional-expense-allocation',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingReportsFunctionalExpensesRoute =
  AuthenticatedAccountingReportsFunctionalExpensesRouteImport.update({
    id: '/reports/functional-expenses',
    path: '/reports/functional-expenses',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingReportsFinancialPositionRoute =
  AuthenticatedAccountingReportsFinancialPositionRouteImport.update({
    id: '/reports/financial-position',
    path: '/reports/financial-position',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingReportsActivitiesRoute =
  AuthenticatedAccountingReportsActivitiesRouteImport.update({
    id: '/reports/activities',
    path: '/reports/activities',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalNewRoute =
  AuthenticatedAccountingJournalNewRouteImport.update({
    id: '/journal/new',
    path: '/journal/new',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingJournalEntryIdRoute =
  AuthenticatedAccountingJournalEntryIdRouteImport.update({
    id: '/journal/$entryId',
    path: '/journal/$entryId',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedAccountingBankBankAccountIdRoute =
  AuthenticatedAccountingBankBankAccountIdRouteImport.update({
    id: '/bank/$bankAccountId',
    path: '/bank/$bankAccountId',
    getParentRoute: () => AuthenticatedAccountingRoute,
  } as any)
const AuthenticatedGrantsGrantIdRestrictionsTermIdRoute =
  AuthenticatedGrantsGrantIdRestrictionsTermIdRouteImport.update({
    id: '/grants/$grantId_/restrictions/$termId',
    path: '/grants/$grantId/restrictions/$termId',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/grants/$grantId_.restrictions.$termId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/confirm-plan': typeof AuthenticatedConfirmPlanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evidence-bundles': typeof AuthenticatedEvidenceBundlesRouteWithChildren
  '/help': typeof AuthenticatedHelpRoute
  '/import': typeof AuthenticatedImportRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/select-plan': typeof AuthenticatedSelectPlanRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/': typeof PortalIndexRoute
  '/accounting/anomalies': typeof AuthenticatedAccountingAnomaliesRoute
  '/accounting/chart-of-accounts': typeof AuthenticatedAccountingChartOfAccountsRoute
  '/accounting/integrations': typeof AuthenticatedAccountingIntegrationsRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/recurring': typeof AuthenticatedAccountingRecurringRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/award-intake/$extractionId': typeof AuthenticatedAwardIntakeExtractionIdRoute
  '/deadlines/calendar': typeof AuthenticatedDeadlinesCalendarRoute
  '/donors/$contactId': typeof AuthenticatedDonorsContactIdRoute
  '/donors/at-risk': typeof AuthenticatedDonorsAtRiskRoute
  '/donors/email': typeof AuthenticatedDonorsEmailRoute
  '/donors/pledges': typeof AuthenticatedDonorsPledgesRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/evidence-bundles/$bundleId': typeof AuthenticatedEvidenceBundlesBundleIdRoute
  '/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
  '/funds/$fundId': typeof AuthenticatedFundsFundIdRoute
  '/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/grants/pipeline': typeof AuthenticatedGrantsPipelineRoute
  '/grants/sentinel': typeof AuthenticatedGrantsSentinelRoute
  '/payments/$requestId': typeof AuthenticatedPaymentsRequestIdRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/reports/ask-ledger': typeof AuthenticatedReportsAskLedgerRoute
  '/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/reports/drafts': typeof AuthenticatedReportsDraftsRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/entities': typeof AuthenticatedSettingsEntitiesRoute
  '/settings/portal-access': typeof AuthenticatedSettingsPortalAccessRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/subrecipients/$subrecipientId': typeof AuthenticatedSubrecipientsSubrecipientIdRoute
  '/portal/bundles/$id': typeof PortalBundlesIdRoute
  '/portal/documents/$id': typeof PortalDocumentsIdRoute
  '/portal/funds/$id': typeof PortalFundsIdRoute
  '/portal/generated-reports/$id': typeof PortalGeneratedReportsIdRoute
  '/portal/grants/$id': typeof PortalGrantsIdRoute
  '/portal/programs/$id': typeof PortalProgramsIdRoute
  '/portal/restriction-terms/$id': typeof PortalRestrictionTermsIdRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/deadlines/': typeof AuthenticatedDeadlinesIndexRoute
  '/donors/': typeof AuthenticatedDonorsIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/evidence-bundles/': typeof AuthenticatedEvidenceBundlesIndexRoute
  '/funders/': typeof AuthenticatedFundersIndexRoute
  '/funds/': typeof AuthenticatedFundsIndexRoute
  '/grants/': typeof AuthenticatedGrantsIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/programs/': typeof AuthenticatedProgramsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/subrecipients/': typeof AuthenticatedSubrecipientsIndexRoute
  '/accounting/bank/$bankAccountId': typeof AuthenticatedAccountingBankBankAccountIdRoute
  '/accounting/journal/$entryId': typeof AuthenticatedAccountingJournalEntryIdRoute
  '/accounting/journal/new': typeof AuthenticatedAccountingJournalNewRoute
  '/accounting/reports/activities': typeof AuthenticatedAccountingReportsActivitiesRoute
  '/accounting/reports/financial-position': typeof AuthenticatedAccountingReportsFinancialPositionRoute
  '/accounting/reports/functional-expenses': typeof AuthenticatedAccountingReportsFunctionalExpensesRoute
  '/accounting/studios/functional-expense-allocation': typeof AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute
  '/accounting/bank/': typeof AuthenticatedAccountingBankIndexRoute
  '/accounting/journal/': typeof AuthenticatedAccountingJournalIndexRoute
  '/grants/$grantId/restrictions/$termId': typeof AuthenticatedGrantsGrantIdRestrictionsTermIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/confirm-plan': typeof AuthenticatedConfirmPlanRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/import': typeof AuthenticatedImportRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/radar': typeof AuthenticatedRadarRoute
  '/select-plan': typeof AuthenticatedSelectPlanRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal': typeof PortalIndexRoute
  '/accounting/anomalies': typeof AuthenticatedAccountingAnomaliesRoute
  '/accounting/chart-of-accounts': typeof AuthenticatedAccountingChartOfAccountsRoute
  '/accounting/integrations': typeof AuthenticatedAccountingIntegrationsRoute
  '/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/accounting/recurring': typeof AuthenticatedAccountingRecurringRoute
  '/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/award-intake/$extractionId': typeof AuthenticatedAwardIntakeExtractionIdRoute
  '/deadlines/calendar': typeof AuthenticatedDeadlinesCalendarRoute
  '/donors/$contactId': typeof AuthenticatedDonorsContactIdRoute
  '/donors/at-risk': typeof AuthenticatedDonorsAtRiskRoute
  '/donors/email': typeof AuthenticatedDonorsEmailRoute
  '/donors/pledges': typeof AuthenticatedDonorsPledgesRoute
  '/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/evidence-bundles/$bundleId': typeof AuthenticatedEvidenceBundlesBundleIdRoute
  '/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
  '/funds/$fundId': typeof AuthenticatedFundsFundIdRoute
  '/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/grants/pipeline': typeof AuthenticatedGrantsPipelineRoute
  '/grants/sentinel': typeof AuthenticatedGrantsSentinelRoute
  '/payments/$requestId': typeof AuthenticatedPaymentsRequestIdRoute
  '/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/reports/ask-ledger': typeof AuthenticatedReportsAskLedgerRoute
  '/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/reports/drafts': typeof AuthenticatedReportsDraftsRoute
  '/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/settings/entities': typeof AuthenticatedSettingsEntitiesRoute
  '/settings/portal-access': typeof AuthenticatedSettingsPortalAccessRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/subrecipients/$subrecipientId': typeof AuthenticatedSubrecipientsSubrecipientIdRoute
  '/portal/bundles/$id': typeof PortalBundlesIdRoute
  '/portal/documents/$id': typeof PortalDocumentsIdRoute
  '/portal/funds/$id': typeof PortalFundsIdRoute
  '/portal/generated-reports/$id': typeof PortalGeneratedReportsIdRoute
  '/portal/grants/$id': typeof PortalGrantsIdRoute
  '/portal/programs/$id': typeof PortalProgramsIdRoute
  '/portal/restriction-terms/$id': typeof PortalRestrictionTermsIdRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/deadlines': typeof AuthenticatedDeadlinesIndexRoute
  '/donors': typeof AuthenticatedDonorsIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/evidence-bundles': typeof AuthenticatedEvidenceBundlesIndexRoute
  '/funders': typeof AuthenticatedFundersIndexRoute
  '/funds': typeof AuthenticatedFundsIndexRoute
  '/grants': typeof AuthenticatedGrantsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/programs': typeof AuthenticatedProgramsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/subrecipients': typeof AuthenticatedSubrecipientsIndexRoute
  '/accounting/bank/$bankAccountId': typeof AuthenticatedAccountingBankBankAccountIdRoute
  '/accounting/journal/$entryId': typeof AuthenticatedAccountingJournalEntryIdRoute
  '/accounting/journal/new': typeof AuthenticatedAccountingJournalNewRoute
  '/accounting/reports/activities': typeof AuthenticatedAccountingReportsActivitiesRoute
  '/accounting/reports/financial-position': typeof AuthenticatedAccountingReportsFinancialPositionRoute
  '/accounting/reports/functional-expenses': typeof AuthenticatedAccountingReportsFunctionalExpensesRoute
  '/accounting/studios/functional-expense-allocation': typeof AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute
  '/accounting/bank': typeof AuthenticatedAccountingBankIndexRoute
  '/accounting/journal': typeof AuthenticatedAccountingJournalIndexRoute
  '/grants/$grantId/restrictions/$termId': typeof AuthenticatedGrantsGrantIdRestrictionsTermIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/accounting': typeof AuthenticatedAccountingRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/confirm-plan': typeof AuthenticatedConfirmPlanRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evidence-bundles': typeof AuthenticatedEvidenceBundlesRouteWithChildren
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRoute
  '/_authenticated/select-plan': typeof AuthenticatedSelectPlanRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/portal/$token': typeof PortalTokenRoute
  '/portal/home': typeof PortalHomeRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/accounting/anomalies': typeof AuthenticatedAccountingAnomaliesRoute
  '/_authenticated/accounting/chart-of-accounts': typeof AuthenticatedAccountingChartOfAccountsRoute
  '/_authenticated/accounting/integrations': typeof AuthenticatedAccountingIntegrationsRoute
  '/_authenticated/accounting/ledger': typeof AuthenticatedAccountingLedgerRoute
  '/_authenticated/accounting/periods': typeof AuthenticatedAccountingPeriodsRoute
  '/_authenticated/accounting/recurring': typeof AuthenticatedAccountingRecurringRoute
  '/_authenticated/accounting/trial-balance': typeof AuthenticatedAccountingTrialBalanceRoute
  '/_authenticated/award-intake/$extractionId': typeof AuthenticatedAwardIntakeExtractionIdRoute
  '/_authenticated/deadlines/calendar': typeof AuthenticatedDeadlinesCalendarRoute
  '/_authenticated/donors/$contactId': typeof AuthenticatedDonorsContactIdRoute
  '/_authenticated/donors/at-risk': typeof AuthenticatedDonorsAtRiskRoute
  '/_authenticated/donors/email': typeof AuthenticatedDonorsEmailRoute
  '/_authenticated/donors/pledges': typeof AuthenticatedDonorsPledgesRoute
  '/_authenticated/events/$eventId': typeof AuthenticatedEventsEventIdRoute
  '/_authenticated/evidence-bundles/$bundleId': typeof AuthenticatedEvidenceBundlesBundleIdRoute
  '/_authenticated/funders/$funderId': typeof AuthenticatedFundersFunderIdRoute
  '/_authenticated/funds/$fundId': typeof AuthenticatedFundsFundIdRoute
  '/_authenticated/grants/$grantId': typeof AuthenticatedGrantsGrantIdRoute
  '/_authenticated/grants/pipeline': typeof AuthenticatedGrantsPipelineRoute
  '/_authenticated/grants/sentinel': typeof AuthenticatedGrantsSentinelRoute
  '/_authenticated/payments/$requestId': typeof AuthenticatedPaymentsRequestIdRoute
  '/_authenticated/programs/$programId': typeof AuthenticatedProgramsProgramIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/reports/ask-ledger': typeof AuthenticatedReportsAskLedgerRoute
  '/_authenticated/reports/builder': typeof AuthenticatedReportsBuilderRoute
  '/_authenticated/reports/drafts': typeof AuthenticatedReportsDraftsRoute
  '/_authenticated/settings/billing': typeof AuthenticatedSettingsBillingRoute
  '/_authenticated/settings/entities': typeof AuthenticatedSettingsEntitiesRoute
  '/_authenticated/settings/portal-access': typeof AuthenticatedSettingsPortalAccessRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/subrecipients/$subrecipientId': typeof AuthenticatedSubrecipientsSubrecipientIdRoute
  '/portal/bundles/$id': typeof PortalBundlesIdRoute
  '/portal/documents/$id': typeof PortalDocumentsIdRoute
  '/portal/funds/$id': typeof PortalFundsIdRoute
  '/portal/generated-reports/$id': typeof PortalGeneratedReportsIdRoute
  '/portal/grants/$id': typeof PortalGrantsIdRoute
  '/portal/programs/$id': typeof PortalProgramsIdRoute
  '/portal/restriction-terms/$id': typeof PortalRestrictionTermsIdRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/deadlines/': typeof AuthenticatedDeadlinesIndexRoute
  '/_authenticated/donors/': typeof AuthenticatedDonorsIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/evidence-bundles/': typeof AuthenticatedEvidenceBundlesIndexRoute
  '/_authenticated/funders/': typeof AuthenticatedFundersIndexRoute
  '/_authenticated/funds/': typeof AuthenticatedFundsIndexRoute
  '/_authenticated/grants/': typeof AuthenticatedGrantsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/programs/': typeof AuthenticatedProgramsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/subrecipients/': typeof AuthenticatedSubrecipientsIndexRoute
  '/_authenticated/accounting/bank/$bankAccountId': typeof AuthenticatedAccountingBankBankAccountIdRoute
  '/_authenticated/accounting/journal/$entryId': typeof AuthenticatedAccountingJournalEntryIdRoute
  '/_authenticated/accounting/journal/new': typeof AuthenticatedAccountingJournalNewRoute
  '/_authenticated/accounting/reports/activities': typeof AuthenticatedAccountingReportsActivitiesRoute
  '/_authenticated/accounting/reports/financial-position': typeof AuthenticatedAccountingReportsFinancialPositionRoute
  '/_authenticated/accounting/reports/functional-expenses': typeof AuthenticatedAccountingReportsFunctionalExpensesRoute
  '/_authenticated/accounting/studios/functional-expense-allocation': typeof AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute
  '/_authenticated/accounting/bank/': typeof AuthenticatedAccountingBankIndexRoute
  '/_authenticated/accounting/journal/': typeof AuthenticatedAccountingJournalIndexRoute
  '/_authenticated/grants/$grantId_/restrictions/$termId': typeof AuthenticatedGrantsGrantIdRestrictionsTermIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/signup'
    | '/accounting'
    | '/activity'
    | '/calendar'
    | '/confirm-plan'
    | '/dashboard'
    | '/evidence-bundles'
    | '/help'
    | '/import'
    | '/notifications'
    | '/onboarding'
    | '/radar'
    | '/select-plan'
    | '/settings'
    | '/invite/$token'
    | '/portal/$token'
    | '/portal/home'
    | '/portal/'
    | '/accounting/anomalies'
    | '/accounting/chart-of-accounts'
    | '/accounting/integrations'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/recurring'
    | '/accounting/trial-balance'
    | '/award-intake/$extractionId'
    | '/deadlines/calendar'
    | '/donors/$contactId'
    | '/donors/at-risk'
    | '/donors/email'
    | '/donors/pledges'
    | '/events/$eventId'
    | '/evidence-bundles/$bundleId'
    | '/funders/$funderId'
    | '/funds/$fundId'
    | '/grants/$grantId'
    | '/grants/pipeline'
    | '/grants/sentinel'
    | '/payments/$requestId'
    | '/programs/$programId'
    | '/reports/$reportId'
    | '/reports/ask-ledger'
    | '/reports/builder'
    | '/reports/drafts'
    | '/settings/billing'
    | '/settings/entities'
    | '/settings/portal-access'
    | '/settings/team'
    | '/subrecipients/$subrecipientId'
    | '/portal/bundles/$id'
    | '/portal/documents/$id'
    | '/portal/funds/$id'
    | '/portal/generated-reports/$id'
    | '/portal/grants/$id'
    | '/portal/programs/$id'
    | '/portal/restriction-terms/$id'
    | '/accounting/'
    | '/deadlines/'
    | '/donors/'
    | '/events/'
    | '/evidence-bundles/'
    | '/funders/'
    | '/funds/'
    | '/grants/'
    | '/payments/'
    | '/programs/'
    | '/reports/'
    | '/subrecipients/'
    | '/accounting/bank/$bankAccountId'
    | '/accounting/journal/$entryId'
    | '/accounting/journal/new'
    | '/accounting/reports/activities'
    | '/accounting/reports/financial-position'
    | '/accounting/reports/functional-expenses'
    | '/accounting/studios/functional-expense-allocation'
    | '/accounting/bank/'
    | '/accounting/journal/'
    | '/grants/$grantId/restrictions/$termId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/activity'
    | '/calendar'
    | '/confirm-plan'
    | '/dashboard'
    | '/help'
    | '/import'
    | '/notifications'
    | '/onboarding'
    | '/radar'
    | '/select-plan'
    | '/settings'
    | '/invite/$token'
    | '/portal/$token'
    | '/portal/home'
    | '/portal'
    | '/accounting/anomalies'
    | '/accounting/chart-of-accounts'
    | '/accounting/integrations'
    | '/accounting/ledger'
    | '/accounting/periods'
    | '/accounting/recurring'
    | '/accounting/trial-balance'
    | '/award-intake/$extractionId'
    | '/deadlines/calendar'
    | '/donors/$contactId'
    | '/donors/at-risk'
    | '/donors/email'
    | '/donors/pledges'
    | '/events/$eventId'
    | '/evidence-bundles/$bundleId'
    | '/funders/$funderId'
    | '/funds/$fundId'
    | '/grants/$grantId'
    | '/grants/pipeline'
    | '/grants/sentinel'
    | '/payments/$requestId'
    | '/programs/$programId'
    | '/reports/$reportId'
    | '/reports/ask-ledger'
    | '/reports/builder'
    | '/reports/drafts'
    | '/settings/billing'
    | '/settings/entities'
    | '/settings/portal-access'
    | '/settings/team'
    | '/subrecipients/$subrecipientId'
    | '/portal/bundles/$id'
    | '/portal/documents/$id'
    | '/portal/funds/$id'
    | '/portal/generated-reports/$id'
    | '/portal/grants/$id'
    | '/portal/programs/$id'
    | '/portal/restriction-terms/$id'
    | '/accounting'
    | '/deadlines'
    | '/donors'
    | '/events'
    | '/evidence-bundles'
    | '/funders'
    | '/funds'
    | '/grants'
    | '/payments'
    | '/programs'
    | '/reports'
    | '/subrecipients'
    | '/accounting/bank/$bankAccountId'
    | '/accounting/journal/$entryId'
    | '/accounting/journal/new'
    | '/accounting/reports/activities'
    | '/accounting/reports/financial-position'
    | '/accounting/reports/functional-expenses'
    | '/accounting/studios/functional-expense-allocation'
    | '/accounting/bank'
    | '/accounting/journal'
    | '/grants/$grantId/restrictions/$termId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/accounting'
    | '/_authenticated/activity'
    | '/_authenticated/calendar'
    | '/_authenticated/confirm-plan'
    | '/_authenticated/dashboard'
    | '/_authenticated/evidence-bundles'
    | '/_authenticated/help'
    | '/_authenticated/import'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/radar'
    | '/_authenticated/select-plan'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/portal/$token'
    | '/portal/home'
    | '/portal/'
    | '/_authenticated/accounting/anomalies'
    | '/_authenticated/accounting/chart-of-accounts'
    | '/_authenticated/accounting/integrations'
    | '/_authenticated/accounting/ledger'
    | '/_authenticated/accounting/periods'
    | '/_authenticated/accounting/recurring'
    | '/_authenticated/accounting/trial-balance'
    | '/_authenticated/award-intake/$extractionId'
    | '/_authenticated/deadlines/calendar'
    | '/_authenticated/donors/$contactId'
    | '/_authenticated/donors/at-risk'
    | '/_authenticated/donors/email'
    | '/_authenticated/donors/pledges'
    | '/_authenticated/events/$eventId'
    | '/_authenticated/evidence-bundles/$bundleId'
    | '/_authenticated/funders/$funderId'
    | '/_authenticated/funds/$fundId'
    | '/_authenticated/grants/$grantId'
    | '/_authenticated/grants/pipeline'
    | '/_authenticated/grants/sentinel'
    | '/_authenticated/payments/$requestId'
    | '/_authenticated/programs/$programId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/reports/ask-ledger'
    | '/_authenticated/reports/builder'
    | '/_authenticated/reports/drafts'
    | '/_authenticated/settings/billing'
    | '/_authenticated/settings/entities'
    | '/_authenticated/settings/portal-access'
    | '/_authenticated/settings/team'
    | '/_authenticated/subrecipients/$subrecipientId'
    | '/portal/bundles/$id'
    | '/portal/documents/$id'
    | '/portal/funds/$id'
    | '/portal/generated-reports/$id'
    | '/portal/grants/$id'
    | '/portal/programs/$id'
    | '/portal/restriction-terms/$id'
    | '/_authenticated/accounting/'
    | '/_authenticated/deadlines/'
    | '/_authenticated/donors/'
    | '/_authenticated/events/'
    | '/_authenticated/evidence-bundles/'
    | '/_authenticated/funders/'
    | '/_authenticated/funds/'
    | '/_authenticated/grants/'
    | '/_authenticated/payments/'
    | '/_authenticated/programs/'
    | '/_authenticated/reports/'
    | '/_authenticated/subrecipients/'
    | '/_authenticated/accounting/bank/$bankAccountId'
    | '/_authenticated/accounting/journal/$entryId'
    | '/_authenticated/accounting/journal/new'
    | '/_authenticated/accounting/reports/activities'
    | '/_authenticated/accounting/reports/financial-position'
    | '/_authenticated/accounting/reports/functional-expenses'
    | '/_authenticated/accounting/studios/functional-expense-allocation'
    | '/_authenticated/accounting/bank/'
    | '/_authenticated/accounting/journal/'
    | '/_authenticated/grants/$grantId_/restrictions/$termId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/home': {
      id: '/portal/home'
      path: '/home'
      fullPath: '/portal/home'
      preLoaderRoute: typeof PortalHomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof PortalRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/select-plan': {
      id: '/_authenticated/select-plan'
      path: '/select-plan'
      fullPath: '/select-plan'
      preLoaderRoute: typeof AuthenticatedSelectPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evidence-bundles': {
      id: '/_authenticated/evidence-bundles'
      path: '/evidence-bundles'
      fullPath: '/evidence-bundles'
      preLoaderRoute: typeof AuthenticatedEvidenceBundlesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/confirm-plan': {
      id: '/_authenticated/confirm-plan'
      path: '/confirm-plan'
      fullPath: '/confirm-plan'
      preLoaderRoute: typeof AuthenticatedConfirmPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting': {
      id: '/_authenticated/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAccountingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subrecipients/': {
      id: '/_authenticated/subrecipients/'
      path: '/subrecipients'
      fullPath: '/subrecipients/'
      preLoaderRoute: typeof AuthenticatedSubrecipientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programs/': {
      id: '/_authenticated/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof AuthenticatedProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants/': {
      id: '/_authenticated/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AuthenticatedGrantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funds/': {
      id: '/_authenticated/funds/'
      path: '/funds'
      fullPath: '/funds/'
      preLoaderRoute: typeof AuthenticatedFundsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funders/': {
      id: '/_authenticated/funders/'
      path: '/funders'
      fullPath: '/funders/'
      preLoaderRoute: typeof AuthenticatedFundersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evidence-bundles/': {
      id: '/_authenticated/evidence-bundles/'
      path: '/'
      fullPath: '/evidence-bundles/'
      preLoaderRoute: typeof AuthenticatedEvidenceBundlesIndexRouteImport
      parentRoute: typeof AuthenticatedEvidenceBundlesRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/': {
      id: '/_authenticated/donors/'
      path: '/donors'
      fullPath: '/donors/'
      preLoaderRoute: typeof AuthenticatedDonorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deadlines/': {
      id: '/_authenticated/deadlines/'
      path: '/deadlines'
      fullPath: '/deadlines/'
      preLoaderRoute: typeof AuthenticatedDeadlinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/portal/restriction-terms/$id': {
      id: '/portal/restriction-terms/$id'
      path: '/restriction-terms/$id'
      fullPath: '/portal/restriction-terms/$id'
      preLoaderRoute: typeof PortalRestrictionTermsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/programs/$id': {
      id: '/portal/programs/$id'
      path: '/programs/$id'
      fullPath: '/portal/programs/$id'
      preLoaderRoute: typeof PortalProgramsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/grants/$id': {
      id: '/portal/grants/$id'
      path: '/grants/$id'
      fullPath: '/portal/grants/$id'
      preLoaderRoute: typeof PortalGrantsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/generated-reports/$id': {
      id: '/portal/generated-reports/$id'
      path: '/generated-reports/$id'
      fullPath: '/portal/generated-reports/$id'
      preLoaderRoute: typeof PortalGeneratedReportsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/funds/$id': {
      id: '/portal/funds/$id'
      path: '/funds/$id'
      fullPath: '/portal/funds/$id'
      preLoaderRoute: typeof PortalFundsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents/$id': {
      id: '/portal/documents/$id'
      path: '/documents/$id'
      fullPath: '/portal/documents/$id'
      preLoaderRoute: typeof PortalDocumentsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/bundles/$id': {
      id: '/portal/bundles/$id'
      path: '/bundles/$id'
      fullPath: '/portal/bundles/$id'
      preLoaderRoute: typeof PortalBundlesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/subrecipients/$subrecipientId': {
      id: '/_authenticated/subrecipients/$subrecipientId'
      path: '/subrecipients/$subrecipientId'
      fullPath: '/subrecipients/$subrecipientId'
      preLoaderRoute: typeof AuthenticatedSubrecipientsSubrecipientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/portal-access': {
      id: '/_authenticated/settings/portal-access'
      path: '/portal-access'
      fullPath: '/settings/portal-access'
      preLoaderRoute: typeof AuthenticatedSettingsPortalAccessRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/entities': {
      id: '/_authenticated/settings/entities'
      path: '/entities'
      fullPath: '/settings/entities'
      preLoaderRoute: typeof AuthenticatedSettingsEntitiesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/billing': {
      id: '/_authenticated/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AuthenticatedSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/reports/drafts': {
      id: '/_authenticated/reports/drafts'
      path: '/reports/drafts'
      fullPath: '/reports/drafts'
      preLoaderRoute: typeof AuthenticatedReportsDraftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/builder': {
      id: '/_authenticated/reports/builder'
      path: '/reports/builder'
      fullPath: '/reports/builder'
      preLoaderRoute: typeof AuthenticatedReportsBuilderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/ask-ledger': {
      id: '/_authenticated/reports/ask-ledger'
      path: '/reports/ask-ledger'
      fullPath: '/reports/ask-ledger'
      preLoaderRoute: typeof AuthenticatedReportsAskLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/programs/$programId': {
      id: '/_authenticated/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AuthenticatedProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/$requestId': {
      id: '/_authenticated/payments/$requestId'
      path: '/payments/$requestId'
      fullPath: '/payments/$requestId'
      preLoaderRoute: typeof AuthenticatedPaymentsRequestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants/sentinel': {
      id: '/_authenticated/grants/sentinel'
      path: '/grants/sentinel'
      fullPath: '/grants/sentinel'
      preLoaderRoute: typeof AuthenticatedGrantsSentinelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants/pipeline': {
      id: '/_authenticated/grants/pipeline'
      path: '/grants/pipeline'
      fullPath: '/grants/pipeline'
      preLoaderRoute: typeof AuthenticatedGrantsPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants/$grantId': {
      id: '/_authenticated/grants/$grantId'
      path: '/grants/$grantId'
      fullPath: '/grants/$grantId'
      preLoaderRoute: typeof AuthenticatedGrantsGrantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funds/$fundId': {
      id: '/_authenticated/funds/$fundId'
      path: '/funds/$fundId'
      fullPath: '/funds/$fundId'
      preLoaderRoute: typeof AuthenticatedFundsFundIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funders/$funderId': {
      id: '/_authenticated/funders/$funderId'
      path: '/funders/$funderId'
      fullPath: '/funders/$funderId'
      preLoaderRoute: typeof AuthenticatedFundersFunderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evidence-bundles/$bundleId': {
      id: '/_authenticated/evidence-bundles/$bundleId'
      path: '/$bundleId'
      fullPath: '/evidence-bundles/$bundleId'
      preLoaderRoute: typeof AuthenticatedEvidenceBundlesBundleIdRouteImport
      parentRoute: typeof AuthenticatedEvidenceBundlesRoute
    }
    '/_authenticated/events/$eventId': {
      id: '/_authenticated/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/pledges': {
      id: '/_authenticated/donors/pledges'
      path: '/donors/pledges'
      fullPath: '/donors/pledges'
      preLoaderRoute: typeof AuthenticatedDonorsPledgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/email': {
      id: '/_authenticated/donors/email'
      path: '/donors/email'
      fullPath: '/donors/email'
      preLoaderRoute: typeof AuthenticatedDonorsEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/at-risk': {
      id: '/_authenticated/donors/at-risk'
      path: '/donors/at-risk'
      fullPath: '/donors/at-risk'
      preLoaderRoute: typeof AuthenticatedDonorsAtRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/donors/$contactId': {
      id: '/_authenticated/donors/$contactId'
      path: '/donors/$contactId'
      fullPath: '/donors/$contactId'
      preLoaderRoute: typeof AuthenticatedDonorsContactIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deadlines/calendar': {
      id: '/_authenticated/deadlines/calendar'
      path: '/deadlines/calendar'
      fullPath: '/deadlines/calendar'
      preLoaderRoute: typeof AuthenticatedDeadlinesCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/award-intake/$extractionId': {
      id: '/_authenticated/award-intake/$extractionId'
      path: '/award-intake/$extractionId'
      fullPath: '/award-intake/$extractionId'
      preLoaderRoute: typeof AuthenticatedAwardIntakeExtractionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/trial-balance': {
      id: '/_authenticated/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AuthenticatedAccountingTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/recurring': {
      id: '/_authenticated/accounting/recurring'
      path: '/recurring'
      fullPath: '/accounting/recurring'
      preLoaderRoute: typeof AuthenticatedAccountingRecurringRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/periods': {
      id: '/_authenticated/accounting/periods'
      path: '/periods'
      fullPath: '/accounting/periods'
      preLoaderRoute: typeof AuthenticatedAccountingPeriodsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/ledger': {
      id: '/_authenticated/accounting/ledger'
      path: '/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AuthenticatedAccountingLedgerRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/integrations': {
      id: '/_authenticated/accounting/integrations'
      path: '/integrations'
      fullPath: '/accounting/integrations'
      preLoaderRoute: typeof AuthenticatedAccountingIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/chart-of-accounts': {
      id: '/_authenticated/accounting/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/accounting/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedAccountingChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/anomalies': {
      id: '/_authenticated/accounting/anomalies'
      path: '/anomalies'
      fullPath: '/accounting/anomalies'
      preLoaderRoute: typeof AuthenticatedAccountingAnomaliesRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journal/': {
      id: '/_authenticated/accounting/journal/'
      path: '/journal'
      fullPath: '/accounting/journal/'
      preLoaderRoute: typeof AuthenticatedAccountingJournalIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/bank/': {
      id: '/_authenticated/accounting/bank/'
      path: '/bank'
      fullPath: '/accounting/bank/'
      preLoaderRoute: typeof AuthenticatedAccountingBankIndexRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/studios/functional-expense-allocation': {
      id: '/_authenticated/accounting/studios/functional-expense-allocation'
      path: '/studios/functional-expense-allocation'
      fullPath: '/accounting/studios/functional-expense-allocation'
      preLoaderRoute: typeof AuthenticatedAccountingStudiosFunctionalExpenseAllocationRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/reports/functional-expenses': {
      id: '/_authenticated/accounting/reports/functional-expenses'
      path: '/reports/functional-expenses'
      fullPath: '/accounting/reports/functional-expenses'
      preLoaderRoute: typeof AuthenticatedAccountingReportsFunctionalExpensesRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/reports/financial-position': {
      id: '/_authenticated/accounting/reports/financial-position'
      path: '/reports/financial-position'
      fullPath: '/accounting/reports/financial-position'
      preLoaderRoute: typeof AuthenticatedAccountingReportsFinancialPositionRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/reports/activities': {
      id: '/_authenticated/accounting/reports/activities'
      path: '/reports/activities'
      fullPath: '/accounting/reports/activities'
      preLoaderRoute: typeof AuthenticatedAccountingReportsActivitiesRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journal/new': {
      id: '/_authenticated/accounting/journal/new'
      path: '/journal/new'
      fullPath: '/accounting/journal/new'
      preLoaderRoute: typeof AuthenticatedAccountingJournalNewRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/journal/$entryId': {
      id: '/_authenticated/accounting/journal/$entryId'
      path: '/journal/$entryId'
      fullPath: '/accounting/journal/$entryId'
      preLoaderRoute: typeof AuthenticatedAccountingJournalEntryIdRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/accounting/bank/$bankAccountId': {
      id: '/_authenticated/accounting/bank/$bankAccountId'
      path: '/bank/$bankAccountId'
      fullPath: '/accounting/bank/$bankAccountId'
      preLoaderRoute: typeof AuthenticatedAccountingBankBankAccountIdRouteImport
      parentRoute: typeof AuthenticatedAccountingRoute
    }
    '/_authenticated/grants/$grantId_/restrictions/$termId': {
      id: '/_authenticated/grants/$grantId_/restrictions/$termId'
      path: '/grants/$grantId/restrictions/$termId'
      fullPath: '/grants/$grantId/restrictions/$termId'
      preLoaderRoute: typeof AuthenticatedGrantsGrantIdRestrictionsTermIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAccountingRouteChildren {
  AuthenticatedAccountingAnomaliesRoute: typeof AuthenticatedAccountingAnomaliesRoute
  AuthenticatedAccountingChartOfAccountsRoute: typeof AuthenticatedAccountingChartOfAccountsRoute
  AuthenticatedAccountingIntegrationsRoute: typeof AuthenticatedAccountingIntegrationsRoute
  AuthenticatedAccountingLedgerRoute: typeof AuthenticatedAccountingLedgerRoute
  AuthenticatedAccountingPeriodsRoute: typeof AuthenticatedAccountingPeriodsRoute
  AuthenticatedAccountingRecurringRoute: typeof AuthenticatedAccountingRecurringRoute
  AuthenticatedAccountingTrialBalanceRoute: typeof AuthenticatedAccountingTrialBalanceRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
  AuthenticatedAccountingBankBankAccountIdRoute: typeof AuthenticatedAccountingBankBankAccountIdRoute
  AuthenticatedAccountingJournalEntryIdRoute: typeof AuthenticatedAccountingJournalEntryIdRoute
  AuthenticatedAccountingJournalNewRoute: typeof AuthenticatedAccountingJournalNewRoute
  AuthenticatedAccountingReportsActivitiesRoute: typeof AuthenticatedAccountingReportsActivitiesRoute
  AuthenticatedAccountingReportsFinancialPositionRoute: typeof AuthenticatedAccountingReportsFinancialPositionRoute
  AuthenticatedAccountingReportsFunctionalExpensesRoute: typeof AuthenticatedAccountingReportsFunctionalExpensesRoute
  AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute: typeof AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute
  AuthenticatedAccountingBankIndexRoute: typeof AuthenticatedAccountingBankIndexRoute
  AuthenticatedAccountingJournalIndexRoute: typeof AuthenticatedAccountingJournalIndexRoute
}

const AuthenticatedAccountingRouteChildren: AuthenticatedAccountingRouteChildren =
  {
    AuthenticatedAccountingAnomaliesRoute:
      AuthenticatedAccountingAnomaliesRoute,
    AuthenticatedAccountingChartOfAccountsRoute:
      AuthenticatedAccountingChartOfAccountsRoute,
    AuthenticatedAccountingIntegrationsRoute:
      AuthenticatedAccountingIntegrationsRoute,
    AuthenticatedAccountingLedgerRoute: AuthenticatedAccountingLedgerRoute,
    AuthenticatedAccountingPeriodsRoute: AuthenticatedAccountingPeriodsRoute,
    AuthenticatedAccountingRecurringRoute:
      AuthenticatedAccountingRecurringRoute,
    AuthenticatedAccountingTrialBalanceRoute:
      AuthenticatedAccountingTrialBalanceRoute,
    AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
    AuthenticatedAccountingBankBankAccountIdRoute:
      AuthenticatedAccountingBankBankAccountIdRoute,
    AuthenticatedAccountingJournalEntryIdRoute:
      AuthenticatedAccountingJournalEntryIdRoute,
    AuthenticatedAccountingJournalNewRoute:
      AuthenticatedAccountingJournalNewRoute,
    AuthenticatedAccountingReportsActivitiesRoute:
      AuthenticatedAccountingReportsActivitiesRoute,
    AuthenticatedAccountingReportsFinancialPositionRoute:
      AuthenticatedAccountingReportsFinancialPositionRoute,
    AuthenticatedAccountingReportsFunctionalExpensesRoute:
      AuthenticatedAccountingReportsFunctionalExpensesRoute,
    AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute:
      AuthenticatedAccountingStudiosFunctionalExpenseAllocationRoute,
    AuthenticatedAccountingBankIndexRoute:
      AuthenticatedAccountingBankIndexRoute,
    AuthenticatedAccountingJournalIndexRoute:
      AuthenticatedAccountingJournalIndexRoute,
  }

const AuthenticatedAccountingRouteWithChildren =
  AuthenticatedAccountingRoute._addFileChildren(
    AuthenticatedAccountingRouteChildren,
  )

interface AuthenticatedEvidenceBundlesRouteChildren {
  AuthenticatedEvidenceBundlesBundleIdRoute: typeof AuthenticatedEvidenceBundlesBundleIdRoute
  AuthenticatedEvidenceBundlesIndexRoute: typeof AuthenticatedEvidenceBundlesIndexRoute
}

const AuthenticatedEvidenceBundlesRouteChildren: AuthenticatedEvidenceBundlesRouteChildren =
  {
    AuthenticatedEvidenceBundlesBundleIdRoute:
      AuthenticatedEvidenceBundlesBundleIdRoute,
    AuthenticatedEvidenceBundlesIndexRoute:
      AuthenticatedEvidenceBundlesIndexRoute,
  }

const AuthenticatedEvidenceBundlesRouteWithChildren =
  AuthenticatedEvidenceBundlesRoute._addFileChildren(
    AuthenticatedEvidenceBundlesRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsBillingRoute: typeof AuthenticatedSettingsBillingRoute
  AuthenticatedSettingsEntitiesRoute: typeof AuthenticatedSettingsEntitiesRoute
  AuthenticatedSettingsPortalAccessRoute: typeof AuthenticatedSettingsPortalAccessRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsBillingRoute: AuthenticatedSettingsBillingRoute,
  AuthenticatedSettingsEntitiesRoute: AuthenticatedSettingsEntitiesRoute,
  AuthenticatedSettingsPortalAccessRoute:
    AuthenticatedSettingsPortalAccessRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAccountingRoute: typeof AuthenticatedAccountingRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedConfirmPlanRoute: typeof AuthenticatedConfirmPlanRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvidenceBundlesRoute: typeof AuthenticatedEvidenceBundlesRouteWithChildren
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRoute
  AuthenticatedSelectPlanRoute: typeof AuthenticatedSelectPlanRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedAwardIntakeExtractionIdRoute: typeof AuthenticatedAwardIntakeExtractionIdRoute
  AuthenticatedDeadlinesCalendarRoute: typeof AuthenticatedDeadlinesCalendarRoute
  AuthenticatedDonorsContactIdRoute: typeof AuthenticatedDonorsContactIdRoute
  AuthenticatedDonorsAtRiskRoute: typeof AuthenticatedDonorsAtRiskRoute
  AuthenticatedDonorsEmailRoute: typeof AuthenticatedDonorsEmailRoute
  AuthenticatedDonorsPledgesRoute: typeof AuthenticatedDonorsPledgesRoute
  AuthenticatedEventsEventIdRoute: typeof AuthenticatedEventsEventIdRoute
  AuthenticatedFundersFunderIdRoute: typeof AuthenticatedFundersFunderIdRoute
  AuthenticatedFundsFundIdRoute: typeof AuthenticatedFundsFundIdRoute
  AuthenticatedGrantsGrantIdRoute: typeof AuthenticatedGrantsGrantIdRoute
  AuthenticatedGrantsPipelineRoute: typeof AuthenticatedGrantsPipelineRoute
  AuthenticatedGrantsSentinelRoute: typeof AuthenticatedGrantsSentinelRoute
  AuthenticatedPaymentsRequestIdRoute: typeof AuthenticatedPaymentsRequestIdRoute
  AuthenticatedProgramsProgramIdRoute: typeof AuthenticatedProgramsProgramIdRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedReportsAskLedgerRoute: typeof AuthenticatedReportsAskLedgerRoute
  AuthenticatedReportsBuilderRoute: typeof AuthenticatedReportsBuilderRoute
  AuthenticatedReportsDraftsRoute: typeof AuthenticatedReportsDraftsRoute
  AuthenticatedSubrecipientsSubrecipientIdRoute: typeof AuthenticatedSubrecipientsSubrecipientIdRoute
  AuthenticatedDeadlinesIndexRoute: typeof AuthenticatedDeadlinesIndexRoute
  AuthenticatedDonorsIndexRoute: typeof AuthenticatedDonorsIndexRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedFundersIndexRoute: typeof AuthenticatedFundersIndexRoute
  AuthenticatedFundsIndexRoute: typeof AuthenticatedFundsIndexRoute
  AuthenticatedGrantsIndexRoute: typeof AuthenticatedGrantsIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedProgramsIndexRoute: typeof AuthenticatedProgramsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSubrecipientsIndexRoute: typeof AuthenticatedSubrecipientsIndexRoute
  AuthenticatedGrantsGrantIdRestrictionsTermIdRoute: typeof AuthenticatedGrantsGrantIdRestrictionsTermIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountingRoute: AuthenticatedAccountingRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedConfirmPlanRoute: AuthenticatedConfirmPlanRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvidenceBundlesRoute:
    AuthenticatedEvidenceBundlesRouteWithChildren,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRoute,
  AuthenticatedSelectPlanRoute: AuthenticatedSelectPlanRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedAwardIntakeExtractionIdRoute:
    AuthenticatedAwardIntakeExtractionIdRoute,
  AuthenticatedDeadlinesCalendarRoute: AuthenticatedDeadlinesCalendarRoute,
  AuthenticatedDonorsContactIdRoute: AuthenticatedDonorsContactIdRoute,
  AuthenticatedDonorsAtRiskRoute: AuthenticatedDonorsAtRiskRoute,
  AuthenticatedDonorsEmailRoute: AuthenticatedDonorsEmailRoute,
  AuthenticatedDonorsPledgesRoute: AuthenticatedDonorsPledgesRoute,
  AuthenticatedEventsEventIdRoute: AuthenticatedEventsEventIdRoute,
  AuthenticatedFundersFunderIdRoute: AuthenticatedFundersFunderIdRoute,
  AuthenticatedFundsFundIdRoute: AuthenticatedFundsFundIdRoute,
  AuthenticatedGrantsGrantIdRoute: AuthenticatedGrantsGrantIdRoute,
  AuthenticatedGrantsPipelineRoute: AuthenticatedGrantsPipelineRoute,
  AuthenticatedGrantsSentinelRoute: AuthenticatedGrantsSentinelRoute,
  AuthenticatedPaymentsRequestIdRoute: AuthenticatedPaymentsRequestIdRoute,
  AuthenticatedProgramsProgramIdRoute: AuthenticatedProgramsProgramIdRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedReportsAskLedgerRoute: AuthenticatedReportsAskLedgerRoute,
  AuthenticatedReportsBuilderRoute: AuthenticatedReportsBuilderRoute,
  AuthenticatedReportsDraftsRoute: AuthenticatedReportsDraftsRoute,
  AuthenticatedSubrecipientsSubrecipientIdRoute:
    AuthenticatedSubrecipientsSubrecipientIdRoute,
  AuthenticatedDeadlinesIndexRoute: AuthenticatedDeadlinesIndexRoute,
  AuthenticatedDonorsIndexRoute: AuthenticatedDonorsIndexRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedFundersIndexRoute: AuthenticatedFundersIndexRoute,
  AuthenticatedFundsIndexRoute: AuthenticatedFundsIndexRoute,
  AuthenticatedGrantsIndexRoute: AuthenticatedGrantsIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedProgramsIndexRoute: AuthenticatedProgramsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSubrecipientsIndexRoute: AuthenticatedSubrecipientsIndexRoute,
  AuthenticatedGrantsGrantIdRestrictionsTermIdRoute:
    AuthenticatedGrantsGrantIdRestrictionsTermIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalTokenRoute: typeof PortalTokenRoute
  PortalHomeRoute: typeof PortalHomeRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalBundlesIdRoute: typeof PortalBundlesIdRoute
  PortalDocumentsIdRoute: typeof PortalDocumentsIdRoute
  PortalFundsIdRoute: typeof PortalFundsIdRoute
  PortalGeneratedReportsIdRoute: typeof PortalGeneratedReportsIdRoute
  PortalGrantsIdRoute: typeof PortalGrantsIdRoute
  PortalProgramsIdRoute: typeof PortalProgramsIdRoute
  PortalRestrictionTermsIdRoute: typeof PortalRestrictionTermsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalTokenRoute: PortalTokenRoute,
  PortalHomeRoute: PortalHomeRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalBundlesIdRoute: PortalBundlesIdRoute,
  PortalDocumentsIdRoute: PortalDocumentsIdRoute,
  PortalFundsIdRoute: PortalFundsIdRoute,
  PortalGeneratedReportsIdRoute: PortalGeneratedReportsIdRoute,
  PortalGrantsIdRoute: PortalGrantsIdRoute,
  PortalProgramsIdRoute: PortalProgramsIdRoute,
  PortalRestrictionTermsIdRoute: PortalRestrictionTermsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
